package io.twodigits.urlshortener.service;

import io.twodigits.urlshortener.model.URL;
import io.twodigits.urlshortener.model.URLDto;
import io.twodigits.urlshortener.model.URLStats;

import java.util.List;
import java.util.Optional;

public interface URLShortenerService {
    /**
     * Get a list of all URLs that belong to a user.
     *
     * @param username
     * @return a list of URLs
     */
    List<URL> listURLsOfUser(String username);

    /**
     * Get a long URL from a short URL generated by the service.
     *
     * @param shortUrl
     * @return the long URL the short URL directs to
     */
    Optional<URL> getLongUrlByShortUrl(String shortUrl);

    /**
     * Add a new URL to the collection of URLs for a user.
     *
     * @param urlDto
     * @return The URL object which has been created
     */

    Optional<URL> generateShortUrl(URLDto urlDto);

    /**
     * Save the URL object into the repo.
     *
     * @param url
     */
    URL saveShortUrl(URL url);

    /**
     * Get the long URL encoded and stored with a short URL
     *
     * @param url
     * @return the encoded long URL
     */
    Optional<URL> getEncodedUrl(String url);


    /**
     * Get a specific URL of a user by its ID.
     *
     * @param user
     * @param id
     * @return The URL object
     */
    Optional<URL> getURLOfUserById(String user, String id);

    /**
     * Return a specific URL by ID.
     *
     * @param id
     * @return The URL object
     */
    Optional<URL> getURLById(String id);

    /**
     * Delete a specific URL which belongs to a user.
     *
     * @param user
     * @param id
     */
    void deleteUrlOfUserById(String user, String id);

    /**
     * Delete a specific URL by its id.
     *
     * @param id
     */
    void deleteUrlById(String id);

    /**
     * Save a new URLStats object in the repo.
     * @param stats
     */
    URLStats saveURLAccessStatistic(URLStats stats);

    /**
     * Get a list of all the URL access statistics stored for a URL.
     *
     * @param url
     * @return a List of URLStats
     */
    List<URLStats> getURLAccessStatistics(URL url);

    /**
     * Get a list of all the URL access statistics stored for a short URL.
     * @param shortUrl
     * @return a list of URLStats
     */
    List<URLStats> getURLAccessStatisticsByShortUrl(String shortUrl);

}
